### ISSUE TITLE
Is not working with NginxProxyManager

### ISSUE THREAD

**Issue by barart** [majd/ip-curl#1]
Im trying to run this on docker but i have other containers that use port 80, so i have exposed a custom port and i use nginx proxy manager (on other container) to use my domains/subdomains to specific containers ports...

With this configuration, the service does not work because the ip that the service returns is always the NPM container ip

Is there any way to get the real visitor ip?

**Comment by majd** [comment]
Please provide a docker-compose file that reproduces the issue that you are facing so I can take a look.
